### ISSUE TITLE
Make available through unpkg

### ISSUE THREAD

**Issue by lifehackett** [jmlue42/spectral-jsonapi-ruleset#35]
Per the [docs](https://docs.stoplight.io/docs/spectral/7895ff1196448-sharing-and-distributing-rulesets) you can use an http reference to extend a ruleset. When I try to access your ruleset via [unpkg.com](https://unpkg.com/spectral-jsonapi-ruleset) I get the following error

> Cannot find package spectral-jsonapi-ruleset@latest

I believe this is because you haven't created the tag `latest`. Can you add that please?

**Comment by marquje** [comment]
Apologies for the super long response time. This status of this project was in flux for quite a while and has just gone through a large overhaul to be Stoplight.io styleguide friendly.

unpkg.com doesn't have this package as we have not published it to npm as of yet.

If you wish to use the Spectral http method you could point to the raw file on github:

https://[raw.githubusercontent.com/jmlue42/spectral-jsonapi-ruleset/main/.spectral.yml](https://raw.githubusercontent.com/jmlue42/spectral-jsonapi-ruleset/main/.spectral.yml)
